# Generated by Django 4.1 on 2022-09-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tplace',
            new_name='Place',
        ),
    ]
